name: Build & Release 🚀

on:
  push:
    tags:
      - "v*.*.*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rename CV files
        run: |
          mkdir ./docs
          mv README.md ./docs/cv-mikedevpe-migelbaez.md

      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ./docs
          output_dir: migelbaez
          images_dir: ./images
          image_import: ./images
          build_html: false

